// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUdeVA5IXCOP3jmAKkX5l4YrDDcNq25Hc',
    appId: '1:783115824960:web:3a9f98cc8afb9e75a814a5',
    messagingSenderId: '783115824960',
    projectId: 'dartudy-web',
    authDomain: 'dartudy-web.firebaseapp.com',
    storageBucket: 'dartudy-web.firebasestorage.app',
    measurementId: 'G-YP0CWF2E4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsic4KcbLvpYU11yt7QXCaKM-frP5dbzY',
    appId: '1:783115824960:android:572bde4f64cbf2aca814a5',
    messagingSenderId: '783115824960',
    projectId: 'dartudy-web',
    storageBucket: 'dartudy-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKf1WStEZOihjV0Ghty_qocuSB0Z-KRw0',
    appId: '1:783115824960:ios:a1f254fa67f3c5d9a814a5',
    messagingSenderId: '783115824960',
    projectId: 'dartudy-web',
    storageBucket: 'dartudy-web.firebasestorage.app',
    iosBundleId: 'com.example.dartudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKf1WStEZOihjV0Ghty_qocuSB0Z-KRw0',
    appId: '1:783115824960:ios:a1f254fa67f3c5d9a814a5',
    messagingSenderId: '783115824960',
    projectId: 'dartudy-web',
    storageBucket: 'dartudy-web.firebasestorage.app',
    iosBundleId: 'com.example.dartudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUdeVA5IXCOP3jmAKkX5l4YrDDcNq25Hc',
    appId: '1:783115824960:web:92a7646b454ffa38a814a5',
    messagingSenderId: '783115824960',
    projectId: 'dartudy-web',
    authDomain: 'dartudy-web.firebaseapp.com',
    storageBucket: 'dartudy-web.firebasestorage.app',
    measurementId: 'G-7RCJ08Z0E3',
  );
}
